name = "AnnA"
uuid = "8fa55c38-3bf2-4db9-84b3-8b314fb7dbfe"
authors = ["Mathias Fischer <MatFi>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
DataFrames = "0.22"
DataStructures = "0.15, 0.16.1, 0.17, 0.18"
DiffEqBase = "6"
DiffEqCallbacks = "2.16.1"
ForwardDiff = "0.10"
Interpolations = "0.13"
NumericalIntegration = "0.3.2"
OrdinaryDiffEq = "5"
RecursiveArrayTools = "1, 2"
Roots = "1"
Setfield = "0.5, 0.6, 0.7"
SparseDiffTools = "1"
Unitful = "1.7"
julia = "1.5"
